# Generated by Django 3.2.5 on 2021-07-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiffinServicePool', '0008_auto_20210516_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='rating',
        ),
        migrations.AddField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Tiffin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiffinServicePool.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RatingByCoustomerOnVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='3', max_length=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiffinServicePool.customer')),
                ('tiffin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiffinServicePool.tiffin')),
            ],
        ),
        migrations.CreateModel(
            name='RatingByCoustomerOnTiffin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='3', max_length=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiffinServicePool.customer')),
                ('tiffin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiffinServicePool.tiffin')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiffinServicePool.tiffin'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
