# Generated by Django 3.2.5 on 2021-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiffinServicePool', '0012_auto_20210719_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingbycoustomerontiffin',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='ratingbycoustomeronvendor',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
