# Generated by Django 3.2.5 on 2021-07-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiffinServicePool', '0013_auto_20210719_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='tiffin',
        ),
    ]
